apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: default
spec:
  containers:
  - image: nginx:alpine
    name: pod1
    env:
      - name: REF
        valueFrom:
          configMapKeyRef:
            name: truew
            key: ref
    volumeMounts:
    - name: bike
      mountPath: /etc/bike/
  volumes:
    - name: bike
      configMap:
        name: bike